langmodel:
  RUN_MODE: LOCAL
  API:
    OpenAI:
      apikey: ""
      chat_model: "gpt-4o"

    Claude:
      apikey: ""
      chat_model: "claude-3-sonnet-20240229"

    huggingface:
      model: "google/gemma-2-9b-it"
      api_key: ""

embeddingmodel:
  sentensetransformer:
    embedding_model: "snunlp/KR-SBERT-V40K-klueNLI-augSTS"

agent:
  serperkey: ""
  Tavily: ""

upstage:
  apikey: ""

huggingface:
  apikey: ""

minio:
  address: "localhost:9010"
  accesskey: "genai_minio"
  secretkey: "openary_minio"

#FAST API KEY
SECRET_KEY: ""
REFRESH_TOKEN_SECRET_KEY: ""

redis:
  address: "redis://redis:6379"

database:
  vector_db_postgres:
    address: "localhost"
    port: 5432
    id: ""
    pwd: ""
    database: ""

  opds_system_db:
    address: "localhost"
    port: 3306
    id: ""
    pwd: ""
    database: ""

  mongodb:
    mongo_host: "localhost"
    mongo_port: 27017
    mongo_user: ""
    mongo_passwd: ""
    auth_source: "genai_svc_dev"
    chat_history: "llm_chat_history"

mgmt_rest_config:
  port: 9001

api_rest_config:
  port: 9000

external_svc:
  management_service: "http://localhost:9001/mgmt" #internal

mqtt:
  address: "localhost"
  port: 5672
  id: genai
  pwd: openary
  virtualhost: "/"


RABBITMQ_SVC_QUEUE:
  PREPROCES_Q_NAME: "OPDS_PREP_REQ"
  PREPROCES_ROUTEKEY: "OPDS_PREP_REQ"

  SUMMARY_Q_NAME: "OPDS_SUMMARY_REQ"
  SUMMARY_ROUTE_KEY: "OPDS_SUMMARY_REQ"

  EMBEDDING_Q_NAME: "OPDS_EMBEDDING_REQ"
  EMBEDDING_ROUTE_KEY: "OPDS_EMBEDDING_REQ"
